# Homework 1

## Numpy

1) Create a NumPy array with the values [10, 20, 30, 40, 50].

In [4]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(type(arr))

<class 'numpy.ndarray'>


2) Calculate the mean and standard deviation of the elements in a NumPy array.

In [2]:
print(np.mean(arr))
print(np.std(arr))

30.0
14.142135623730951


3) Create a 3x3 NumPy array with random integers between 1 and 100.

In [4]:
import random as rn

matrix = np.array([[rn.randint(1,100) for i in range(3)] for j in range(3)])
print(matrix)

[[ 4 75  1]
 [54 33 93]
 [18 52 55]]


 4) Calculate the square root of each element in a NumPy array.

In [5]:
arr = np.array([10, 20, 30, 40, 50])

#your answer

arr_sqr = np.array([item**(1/2) for item in arr]) 

print(arr_sqr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


5) Create a 2D NumPy array with dimensions (4, 4) filled with ones

In [6]:
#your code
arr_4 = np.array([[1 for i in range(4)] for j in range(4)])
print(arr_4)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


6) Reshape a 1D NumPy array into a 3x3 2D array.

In [115]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# arr_2 = np.array([[arr[j] for j in range((i-1)*3,i*3)] for i in range(1,4)])

arr_2 = np.reshape(arr, (3,3))

arr_2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

7) Create a NumPy array of 10 equally spaced values between 0 and 1.

In [8]:
arr_10 = np.array([1/9 * i for i in range(10)]) 
arr_10

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

8) Find the index of the maximum value in a NumPy array.

In [9]:
arr = np.array([10, 20, 30, 40, 50])

for i in range(len(arr)):
    if arr[i] == np.max(arr):
        k = i 
        
print(k)



4


9) Create a diagonal matrix with specified diagonal elements using NumPy.

In [39]:
x = np.array([[i*10 for i in range((j-1)*3, j*3)] for j in range(1,4)])

print(x)

diag = np.diag(np.diagonal(x))
print(diag)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]
[[ 0  0  0]
 [ 0 40  0]
 [ 0  0 80]]


10) Compute the determinant of a square NumPy matrix.

In [40]:
matrix = np.array([[1,2], [3,4]])


#your answer
print(matrix)
print(np.linalg.det(matrix))

[[1 2]
 [3 4]]
-2.0000000000000004


11) Create a NumPy array with random floats between 0 and 1.

In [47]:
array = np.array([np.random.random() for i in range(3)])
array

array([0.49544539, 0.18580501, 0.13976417])

## Pandas

12) You have a list of names: names = ['Alice', 'Bob', 'Charlie', 'David']. Convert this list into a pandas DataFrame.

In [50]:
import pandas as pd

df = pd.DataFrame(['Alice', 'Bob', 'Charlie', 'David'])

df


0
0    Alice
1      Bob
2  Charlie
3    David

In [100]:
#we have DataFrame df
data = {'Name': ['Tom', 'Joseph', 'Krish', 'John', 'Andy', 'Tiffany', 'Michael'], 
        'Age': [20, 21, 19, 18, 32, 56, 12],
        'Gender': ['M', 'M', 'F', 'M', 'F', 'F', 'M'],}  
df = pd.DataFrame(data)   
print(df)  

      Name  Age Gender
0      Tom   20      M
1   Joseph   21      M
2    Krish   19      F
3     John   18      M
4     Andy   32      F
5  Tiffany   56      F
6  Michael   12      M


13) Given a DataFrame df with a column 'Age', calculate and display the maximum age.

In [62]:
print(max(df['Age']))

56


14) Filter the rows in a DataFrame df where the 'Age' is greater than 30.

In [69]:
data2 = df.loc[df['Age']>=30]
data2

Name  Age Gender
4     Andy   32      F
5  Tiffany   56      F

15) Sort a DataFrame df by the 'Age' column in descending order.

In [133]:
data3 = df.sort_values(by = 'Age', ascending = False)
data3

Name  Age Gender
5  Tiffany   56      F
4     Andy   32      F
1   Joseph   21      M
0      Tom   20      M
2    Krish   19      F
3     John   18      M
6  Michael   12      M

In [122]:
# countries.csv file which is imported
url = "countries.csv"  #write path of countries.csv file in your device

16) Read the .csv file and store it as a pandas Data Frame and define its type

In [137]:
#your code 
dff = pd.read_csv(url)
type(dff)

pandas.core.frame.DataFrame

17) Show the first 7 rows of our Data Frame

In [124]:
#your answer
dff.head(7)

location      continent  population  life_expectancy  \
0          Afghanistan           Asia    38928341            64.83   
1              Albania         Europe     2877800            78.57   
2              Algeria         Africa    43851043            76.88   
3              Andorra         Europe       77265            83.73   
4               Angola         Africa    32866268            61.15   
5             Anguilla  North America       15002            81.88   
6  Antigua and Barbuda  North America       97928            77.02   

   hospital_beds_per_thousand  gdp_per_capita  
0                        0.50        1803.987  
1                        2.89       11803.431  
2                        1.90       13913.839  
3                         NaN             NaN  
4                         NaN        5819.495  
5                         NaN             NaN  
6                        3.80       21490.943

18) Show the last 7 rows of our Data Frame

In [125]:
dff.tail(7)

location      continent  population  life_expectancy  \
203         Vatican         Europe         809            75.12   
204       Venezuela  South America    28435943            72.06   
205         Vietnam           Asia    97338583            75.40   
206  Western Sahara         Africa      597330            70.26   
207           Yemen           Asia    29825968            66.12   
208          Zambia         Africa    18383956            63.89   
209        Zimbabwe         Africa    14862927            61.49   

     hospital_beds_per_thousand  gdp_per_capita  
203                         NaN             NaN  
204                         0.8       16745.022  
205                         2.6        6171.884  
206                         NaN             NaN  
207                         0.7        1479.147  
208                         2.0        3689.251  
209                         1.7        1899.775

19) How many countries does the dataframe 'df' contain? Use the function to print the number of rows and columns in the 'df'

In [151]:
dim = np.shape(dff)
print(dim[0])
print(dim[1])

210
6


20) Count the number of missing values in each columns of 'df'

In [3]:
sums_miss = dff.isnan().sum()
print(sums_miss)

NameError: name 'dff' is not defined

21) Sort the dataframe by 2 variables: 'continent' in ascending order, 'population' in descending order. 

In [167]:
sorted_data = dff.sort_values(by = ['continent', 'population'], ascending = [False, True])

sorted_data = sorted_data.reset_index(drop = True)

sorted_data

location      continent  population  life_expectancy  \
0                Falkland Islands  South America        3483            81.44   
1                        Suriname  South America      586634            71.68   
2                          Guyana  South America      786559            69.91   
3                         Uruguay  South America     3473727            77.91   
4                        Paraguay  South America     7132530            74.25   
..                            ...            ...         ...              ...   
205                      Tanzania         Africa    59734213            65.46   
206  Democratic Republic of Congo         Africa    89561404            60.68   
207                         Egypt         Africa   102334403            71.99   
208                      Ethiopia         Africa   114963583            66.60   
209                       Nigeria         Africa   206139587            54.69   

     hospital_beds_per_thousand  gdp_per_capita  
0                           NaN             NaN  
1                           3.1       13767.119  
2                           1.6        7435.047  
3                           2.8       20551.409  
4                           1.3        8827.010  
..                          ...             ...  
205                         0.7        2683.304  
206                         NaN         808.133  
207                         1.6       10550.206  
208                         0.3        1729.927  
209                         NaN        5338.454  

[210 rows x 6 columns]

 22) Subset rows where 'life_expectancy' is greater than 80.0, and then calculate the number of countries. (Hint: the number of countries can be calculated using the function that prints the number of rows and columns in dataframe)

In [174]:
new_df = dff.loc[dff['life_expectancy'] >= 80] 
print(new_df.shape[0])
print(dff.shape[0])


47
210
