# Practice work - 1

The following five questions are focused around a public library. Staff members are trying to gain insight on current library card holders and have sent out a short survey to them. Read each prompt carefully and determine the variable type for each question.

Q1: Library card holders were asked whether or not they have checked out a book from the library in the past month (yes or no). What type of variable would their response be considered?

Q2: Library card holders were asked to report the amount of late fees they have been charged in the past year (input in the form of $XX.XX). What type of variable would their response be considered? 

Q3:  Library card holders were asked to reflect on their most recent book they checked out and report the genre that it most closely represented (i.e. Science Fiction, Action, Romance, Mystery, etc.). What type of variable would their response be considered?

In [ ]:
#your answer

Q4: The library recently added a new online checkout/renewal system. Library card holders were asked how many times they have used the new online system. What type of variable would their response be considered?

In [ ]:
#your answer

Q5: Library card holders were asked to report the satisfaction of their library experience during their last visit using a 1 to 5 scale (with the following representations: 1 - Extremely Unsatisfied, 2 - Unsatisfied, 3 - Neutral, 4 - Satisfied, 5 - Extremely Satisfied). What type of variable would their response be considered?

In [ ]:
#your answer

Q6: Numpy arrays

In [8]:
import numpy as np
#Create numpy array and find datatype
np1 = np.array([1,2,3])
#your code
print(type(np1))

<class 'numpy.ndarray'>


In [11]:
# Create 4x2 numpy array full of zeros without using array().
zeros1 = np.zeros((4,2))
#your code
print(zeros1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [17]:
#Create 4x3 numpy array full of 6 without using array().
six = np.zeros((4,3))
#your code
print(six + 6)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [4]:
#Create 5x5 numpy array full of random numbers without using array().
import random as rn

random_n = np.randing()

#your code)

In [5]:
#Find shapes of all arrays above

#your code

In [6]:
#Given numpy array, find sum of elements of array by row and column, sum of all elements
x = np.array([[12,5],[31,1]])

#your code

In [7]:
#Given 2 numpy arrays, find addition, subtruction, multiplication, division of 2 arrays
x = np.array([[12,5],[31,4]], dtype=np.float64)
y = np.array([[5,7],[1,8]], dtype=np.float64)

#your code

In [8]:
#Given numpy array, find mean of all elements, each row and each column    
x = np.array([[12,2],[1,10]])

#your code

Q5: Pandas

In [10]:
import pandas as pd
# countries.csv file which is imported
url = "/Users/User/Desktop/Practice2/countries.csv"  #write path of countries.csv file in your device

In [9]:
# Read the .csv file and store it as a pandas Data Frame and define its type

#your code

In [10]:
# Show the first 5 rows of our Data Frame

#your code

In [11]:
# Show the column names and data types of each column

#your code

In [12]:
# Select all rows for multiple columns, ['life_expectancy', 'hospital_beds_per_thousand', 'gdp_per_capita']

#your code

In [13]:
# Select few rows for multiple columns, ['life_expectancy', 'hospital_beds_per_thousand', 'gdp_per_capita']

#your column

In [15]:
# Return all observations of location

#your code

In [16]:
# Show first 7 rows by using iloc()

#your code

In [17]:
# List unique values in the df['continent'] column

#your code

In [18]:
# Group data by 'location' and 'continent' columns

#your code

In [18]:
n = 300
prefer = 75
p = prefer/n
z = 1.96 
SE = (p*(1-p)/n)**(1/2)
ME = SE * z 

lower_bound = p - ME 
upper_bound = p + ME 

print(lower_bound, upper_bound)

0.201 0.299


In [19]:
import math

# Provided data
total_responses = 300
prefer_product_a = 75
confidence_level = 0.95
z_value = 1.96  # Z-value for a 95% confidence interval

# Calculate sample proportion (p)
p = prefer_product_a / total_responses

# Calculate standard error (SE)
se = math.sqrt((p * (1 - p)) / total_responses)

# Calculate margin of error (ME)
me = z_value * se

# Calculate confidence interval bounds
lower_bound = p - me
upper_bound = p + me

# Display the results
print(f"Sample Proportion (p): {p:.4f}")
print(f"Standard Error (SE): {se:.4f}")
print(f"Margin of Error (ME): {me:.4f}")
print(f"Confidence Interval: ({lower_bound:.4f}, {upper_bound:.4f})")


Sample Proportion (p): 0.2500
Standard Error (SE): 0.0250
Margin of Error (ME): 0.0490
Confidence Interval: (0.2010, 0.2990)
